
# About data analysis

## We will talk about two ways to look at stuff one counts

- First, tend things of one kind do sth ever so slightly differently than other kinds of things?

- Second if we have a number of categories are they different from each other

Get rid of as many assumptions as possible

## But first, what day is this?


<img src="Germanic_languages_in_Europe.png">


<img src="Brevmarke_200.jpg">

<img src="Lützen.jpg">

<img src="wasa.gif">


In [1]:
import numpy as np
import math
np.set_printoptions(suppress=True, precision=4)

# Some Example Data

In [2]:
items=np.array([[True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False],
                [22, 33, 12, 74, 32, 42, 23,11, 31, 41, 53, 61, 34, 51, 71, 63, 55],
               ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q"]])


for i in range(len(items[1])):
    print(i," ",items[0,i]," ",items[1,i])


0   True   22
1   True   33
2   True   12
3   True   74
4   True   32
5   True   42
6   True   23
7   False   11
8   False   31
9   False   41
10   False   53
11   False   61
12   False   34
13   False   51
14   False   71
15   False   63
16   False   55


### (Magic Numbers are a Bad Thing)

In [3]:
items=np.array([[True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False],
                [22, 33, 12, 74, 32, 42, 23,11, 31, 41, 53, 61, 34, 51, 71, 63, 55],
               ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q"]])

critcolumn = 0
valuecolumn = 1

for i in range(len(items[0])):
    print(i," ",items[critcolumn,i]," ",items[valuecolumn,i])



0   True   22
1   True   33
2   True   12
3   True   74
4   True   32
5   True   42
6   True   23
7   False   11
8   False   31
9   False   41
10   False   53
11   False   61
12   False   34
13   False   51
14   False   71
15   False   63
16   False   55


In [4]:
for i in range(len(items[0])):
    if items[critcolumn,i]:
        print(i," ",items[critcolumn,i]," ",items[valuecolumn,i])


0   True   22
1   True   33
2   True   12
3   True   74
4   True   32
5   True   42
6   True   23
7   False   11
8   False   31
9   False   41
10   False   53
11   False   61
12   False   34
13   False   51
14   False   71
15   False   63
16   False   55


In [5]:
def str2bool(string):
    if string=="True": 
        return True 
    elif string=="False":
        return False 
    else: 
        raise Exception("Что за черт? This string is not a boolean: \""+string+"\"")

In [8]:
if str2bool("Jussi"):
    print("Huzza!")
else:
    print("Blah.")

Exception: Что за черт? This string is not a boolean: "Jussi"

In [9]:
for i in range(len(items[0])):
    if str2bool(items[critcolumn,i]):
        print(i," ",items[critcolumn,i]," ",items[valuecolumn,i])

0   True   22
1   True   33
2   True   12
3   True   74
4   True   32
5   True   42
6   True   23


## Save effort and time by coding! 

https://xkcd.com/1205/

- Use Modules!

- Use APIs!


In [12]:
print(items)
print("\n")
critcolumn = 0
valuecolumn = 1
debug = False
totnum=0
relnum=0
nonnum=0
totsum=0
relsum=0
nonsum=0
if debug:
    print("i\tcrit\tvalue\tN\tsum\t#rel\trelsum\t#non\tnonsum")

for i in range(len(items[0])):
    totnum += 1
    if str2bool(items[critcolumn,int(i)]):
        relnum += 1
        relsum += float(items[valuecolumn,i])
    else:
        nonnum += 1
        nonsum += float(items[valuecolumn,i])
    totsum += float(items[valuecolumn,i])
    if debug:
        print(i,"\t",items[critcolumn,i],"\t",items[valuecolumn,i],"\t",
              totnum,"\t",totsum,"\t",
              relnum,"\t",relsum,"\t",
              nonnum,"\t",nonsum)

relavscore=0
if relnum > 0:
    relavscore = relsum/relnum
nonavscore=0
if nonnum > 0:
    nonavscore = nonsum/nonnum
totavscore=0
if totnum > 0:
    totavscore = totsum/totnum
 

print(totnum," items seen with ",totavscore," average score")
print("   whereof ",relnum," relevant with sum ",relsum," and average score ",relavscore)
print("   whereof ",nonnum," non-relevant with sum ",nonsum," and average score ",nonavscore)



[['True' 'True' 'True' 'True' 'True' 'True' 'True' 'False' 'False' 'False'
  'False' 'False' 'False' 'False' 'False' 'False' 'False']
 ['22' '33' '12' '74' '32' '42' '23' '11' '31' '41' '53' '61' '34' '51'
  '71' '63' '55']
 ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q']]


17  items seen with  41.705882352941174  average score
   whereof  7  relevant with sum  238.0  and average score  34.0
   whereof  10  non-relevant with sum  471.0  and average score  47.1







- print-style debugging
- working around default typing
- magic numbers

### Exercise 1: Visualisation please!

# Statistical testing

- mean vs median (beware of mean!)
- parametric vs nonparametric

## Sorting matrices

In [19]:
a = np.array([[5,2,3],[8,1,3],[2,3,4]])
#a = np.array([[False,False,True,False,True,False,True],[1,9,4,2,6,5,8],["a","b","c","d","e","f","g"]]) 
print(a) 
print("----------")
c = a[1,:]
print(c)
print("----------")
c = a[1,:].argsort() 
## argsort(axis=-1, kind='quicksort', order=None)	Returns the indices that would sort this array.
print(c) 
print("----------")
d = a[1,c] 
print(d) 
print("----------")
d = a[:,c] 
print(d) 
print("----------")
c = a[:,0].argsort() 
print(c) 
print("----------")
e = a[c,:] 
print(e)


[[5 2 3]
 [8 1 3]
 [2 3 4]]
----------
[8 1 3]
----------
[1 2 0]
----------
[1 3 8]
----------
[[2 3 5]
 [1 3 8]
 [3 4 2]]
----------
[2 0 1]
----------
[[2 3 4]
 [5 2 3]
 [8 1 3]]


## On our little test data

In [20]:
items=np.array([[True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False],
                [22, 33, 12, 74, 32, 42, 23,11, 31, 41, 53, 61, 34, 51, 71, 63, 55],
               ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q"]])


sortedscores=items[1,:].argsort()
print(sortedscores)
sorteditems=items[:,sortedscores]
print(sorteditems)

[ 7  2  0  6  8  4  1 12  9  5 13 10 16 11 15 14  3]
[['False' 'True' 'True' 'True' 'False' 'True' 'True' 'False' 'False' 'True'
  'False' 'False' 'False' 'False' 'False' 'False' 'True']
 ['11' '12' '22' '23' '31' '32' '33' '34' '41' '42' '51' '53' '55' '61'
  '63' '71' '74']
 ['h' 'c' 'a' 'g' 'i' 'e' 'b' 'm' 'j' 'f' 'n' 'k' 'q' 'l' 'p' 'o' 'd']]


## Calculating rank sum and the Mann Whitney U

In [21]:
print(items)
print("\n")
critpos = 0;
valuecolumn = 1
debug = True
totnum=0
relnum=0
nonnum=0
totsum=0
relsum=0
nonsum=0
totranksum=0
relranksum=0
nonranksum=0
print("i\tcrit\tvalue\tN\tsum\t#rel\trel sum\t#non\tnon sum")
sortedscoreindices=items[1,:].argsort()
sorteditems=items[:,sortedscoreindices]
for i in sortedscoreindices:
    totnum += 1
    if str2bool(items[0,i]):
        relnum += 1
        relranksum += totnum
        relsum += float(items[1,i])
    else:
        nonnum += 1
        nonranksum += totnum
        nonsum += float(items[1,i])
    totsum += float(items[1,i])
    totranksum += totnum
    if debug:
        print(i,"\t",items[0,i],"\t",items[1,i],"\t",
              totnum,"\t",totranksum,"\t",
              relnum,"\t",relranksum,"\t",
              nonnum,"\t",nonranksum)

relavscore=0
if relnum > 0:
    relavscore = relsum/relnum
nonavscore=0
if nonnum > 0:
    nonavscore = nonsum/nonnum
totavscore=0
if totnum > 0:
    totavscore = totsum/totnum
 

print(totnum," items seen with ",totavscore," average score")
print("   whereof ",relnum," relevant with rank sum ",relranksum," and average score ",relavscore)
print("   whereof ",nonnum," non-relevant with rank sum ",nonranksum," and average score ",nonavscore)

relu = relranksum-relnum*(relnum+1)/2
nonu = nonranksum-nonnum*(nonnum+1)/2


print("   U-score: ",relu)
print("   or possibly: ",nonu)




[['True' 'True' 'True' 'True' 'True' 'True' 'True' 'False' 'False' 'False'
  'False' 'False' 'False' 'False' 'False' 'False' 'False']
 ['22' '33' '12' '74' '32' '42' '23' '11' '31' '41' '53' '61' '34' '51'
  '71' '63' '55']
 ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q']]


i	crit	value	N	sum	#rel	rel sum	#non	non sum
7 	 False 	 11 	 1 	 1 	 0 	 0 	 1 	 1
2 	 True 	 12 	 2 	 3 	 1 	 2 	 1 	 1
0 	 True 	 22 	 3 	 6 	 2 	 5 	 1 	 1
6 	 True 	 23 	 4 	 10 	 3 	 9 	 1 	 1
8 	 False 	 31 	 5 	 15 	 3 	 9 	 2 	 6
4 	 True 	 32 	 6 	 21 	 4 	 15 	 2 	 6
1 	 True 	 33 	 7 	 28 	 5 	 22 	 2 	 6
12 	 False 	 34 	 8 	 36 	 5 	 22 	 3 	 14
9 	 False 	 41 	 9 	 45 	 5 	 22 	 4 	 23
5 	 True 	 42 	 10 	 55 	 6 	 32 	 4 	 23
13 	 False 	 51 	 11 	 66 	 6 	 32 	 5 	 34
10 	 False 	 53 	 12 	 78 	 6 	 32 	 6 	 46
16 	 False 	 55 	 13 	 91 	 6 	 32 	 7 	 59
11 	 False 	 61 	 14 	 105 	 6 	 32 	 8 	 73
15 	 False 	 63 	 15 	 120 	 6 	 32 	 9 	 88
14 	 False 	 71 	 16 	 136 	 6 	 3





### Exercise 2: Write a function which picks out the median from the items datastructure



- There will be broken matrices.

### Exercise 3: Check to see that the matrix is well formed and raise error if not

- How about ties?

### Exercise 4: Handle ties

- How about items with missing values?

### Exercise 5: Handle items with missing values

- More categories?

### Exercise 6: Handle one category vs many others



# Significance

There are $relnum$ items of interest and $totnum$ ranks. Average rank would be $(totnum+1)/2$; average rank sum for the $relnum$ items of interest should be about $relnum*(totnum+1)/2$. Minimum rank for $relnum$ items is $relnum*(relnum+1)/2$

We use a guess---based on a Gaussian distribution which is at least somewhat reasonable here---for what the standard deviation around those ranks can be to figure out if deviation from that rank sum is interestingly high. 


In [22]:
print("Number of items: ",totnum)
print("Middle rank: ",(totnum+1)/2)
print("Number of items of interest: ",relnum)
print("Expected rank sum for those items: ", relnum*(totnum+1)/2)
print("Observed rank sum: ",relranksum)
print("Minimum possible rank for the ",relnum," items is ",relnum*(relnum+1)/2)
print("U score for the ",relnum," items is ",relranksum-relnum*(relnum+1)/2)
print("Standard deviation: ",math.sqrt(relnum*nonnum*(totnum+1)/12)) #fingers crossed that it is Gaussian enough
print("95% level upper bound: ", relnum*(totnum+1)/2+1.6449*math.sqrt(relnum*nonnum*(totnum+1)/12))
print("95% level lower bound: ", relnum*(totnum+1)/2-1.6449*math.sqrt(relnum*nonnum*(totnum+1)/12))
print("75% level upper bound: ", relnum*(totnum+1)/2+0.675*math.sqrt(relnum*nonnum*(totnum+1)/12))
print("75% level lower bound: ", relnum*(totnum+1)/2-0.675*math.sqrt(relnum*nonnum*(totnum+1)/12))

Number of items:  17
Middle rank:  9.0
Number of items of interest:  7
Expected rank sum for those items:  63.0
Observed rank sum:  49
Minimum possible rank for the  7  items is  28.0
U score for the  7  items is  21.0
Standard deviation:  10.246950765959598
95% level upper bound:  79.85520931492694
95% level lower bound:  46.14479068507306
75% level upper bound:  69.91669176702273
75% level lower bound:  56.083308232977274


# Correlation


- spearman vs pearson



# Categories

jussi@hetimiten:~/Desktop/data$ wc -l *nopar*
  1275472 GH95-nopar-clean.txt
  4027238 LAT94-nopar-clean.txt
  5302710 total
jussi@hetimiten:~/Desktop/data$ grep -cw prayer GH95-nopar-clean.txt 
212
jussi@hetimiten:~/Desktop/data$ grep -cvw prayer GH95-nopar-clean.txt 
1275260
jussi@hetimiten:~/Desktop/data$ grep -cvw prayer LAT94-nopar-clean.txt 
4025924
jussi@hetimiten:~/Desktop/data$ grep -cw prayer LAT94-nopar-clean.txt 
1314

boys' vs girls' first names as first name of first author vs "I"

jussi@hetimiten:~/Desktop/data$ grep -cw "i" clean-boys.GH.en 
69164
jussi@hetimiten:~/Desktop/data$ grep -cvw "i" clean-boys.GH.en 
3790936
jussi@hetimiten:~/Desktop/data$ grep -cvw "i" clean-girls.GH.en 
1020010
jussi@hetimiten:~/Desktop/data$ grep -cw "i" clean-girls.GH.en 
19821

jussi@hetimiten:~/Desktop/data$ grep -cw "i" clean-girls.LAT.en
83718
jussi@hetimiten:~/Desktop/data$ grep -cvw "i" clean-girls.LAT.en
4470148
jussi@hetimiten:~/Desktop/data$ grep -cvw "i" clean-boys.LAT.en
10103925
jussi@hetimiten:~/Desktop/data$ grep -cw "i" clean-boys.LAT.en
181209



In [34]:
#crosstab=np.array([[212,1275260],[1314,4025924]]) #prayer x ukus
crosstab=np.array([[69164,3790936],[19821,1020010]]) #i x gender uk
#crosstab=np.array([[181209,10103925],[83718,4470148]]) #i x gender us

In [25]:
def margins1 (a):
    row0sum = a[0].sum()
    row1sum = a[1].sum()
    col0sum = a[:,0].sum()
    col1sum = a[:,1].sum()
    bign = row0sum+row1sum
    print("_", end = "\t")
    print("_", end = "\t")
    print(row0sum)
    print("_", end = "\t")
    print("_", end = "\t")
    print(row1sum)
    print(col0sum, end = "\t")
    print(col1sum, end = "\t")
    print(bign)
    
margins1(crosstab)

_	_	1275472
_	_	4027238
1526	5301184	5302710


In [26]:
crosstab.shape

(2, 2)

In [27]:
d=crosstab.shape

In [28]:
d[0]

2

In [29]:
def margins2 (a):
    d = a.shape
    if (len (d)  > 2):
        raise("Wrong format for this function")
    rows=d[0]  # unnecessary, but clear
    cols=d[1]  # unnecessary, but clear
    rowsums = np.array([])
    colsums = np.array([])
    bign = 0
    for i in range(rows):
        rowsums = np.insert(rowsums,i,a[i].sum()) # not right! don't use insert here!
    for j in range(cols):
        colsums = np.insert(colsums,j,a[:,j].sum())
    bign = rowsums.sum()
    for k in range(rows):
        for l in range(cols):
            print("_"*len(str(colsums[l])), end = "\t")
        print(rowsums[k])
    for l in range(cols):
        print(colsums[l], end="\t")
    print(bign)

m=margins2(crosstab)

______	_________	1275472.0
______	_________	4027238.0
1526.0	5301184.0	5302710.0


better and more general. but it allows mistakes to be made at runtime!
what happens if unexpected formats are input? rows of varying length? check for it.

lets now try returning a result

In [30]:
def margins3 (a):
    d = a.shape
    if (len (d)  > 2):
        raise("Wrong format for this function")
    rows=d[0]  # unnecessary, but clear
    cols=d[1]  # unnecessary, but clear
    margins = np.zeros((rows+1,cols+1))
    bign = 0
    for i in range(rows):
        margins[i,cols] = a[i].sum()
    for j in range(cols):
        margins[rows,j] = a[:,j].sum()
    margins[rows,cols] = margins[:,cols].sum()
    return margins


m=margins3(crosstab)
print(m)

[[       0.        0.  1275472.]
 [       0.        0.  4027238.]
 [    1526.  5301184.  5302710.]]


In [35]:

def deviation(crosstab):
    d = crosstab.shape
    if (len (d)  > 2):
        raise("Wrong format for this function")
    rows=d[0]  # unnecessary, but clear
    cols=d[1]  # unnecessary, but clear
    print("Degrees of freedom: ",(rows-1)*(cols-1))
    print("Marginal sums:\n")
    expecteds=margins3(crosstab)
    print(expecteds)
    print("\n")
    for k in range(rows):
        for l in range(cols):
            expecteds[k,l]=expecteds[k,cols]*expecteds[rows,l]/expecteds[rows,cols]
    print("Expected values:\n")
    print(expecteds)
    print("\n")
    sum = 0;   # oops, perl semicolon here. won't hurt but should not be there.
    deviation=np.zeros((rows+1,cols+1))
    for k in range(rows):
        for l in range(cols):
            deviation[k,l]=((expecteds[k,l]-crosstab[k,l]))

    print("A reminder about the observed values:")
    print("\n")
    print(crosstab)
    print("\n")
    print("Deviation from expected values:")
    print("\n")
    print(deviation)
    print("\n")

deviation(crosstab)

Degrees of freedom:  1
Marginal sums:

[[       0.        0.  3860100.]
 [       0.        0.  1039831.]
 [   88985.  4810946.  4899931.]]


Expected values:

[[   70101.1909  3789998.8091  3860100.    ]
 [   18883.8091  1020947.1909  1039831.    ]
 [   88985.      4810946.      4899931.    ]]


A reminder about the observed values:


[[  69164 3790936]
 [  19821 1020010]]


Deviation from expected values:


[[ 937.1909 -937.1909    0.    ]
 [-937.1909  937.1909    0.    ]
 [   0.        0.        0.    ]]




## The $\chi^2$ measure

Now let's quantify that deviation!
Large deviation: strange; small deviation: less strange.
We will use $\chi²$. It depends on *degree of freedom* of the contingency table. 


In [36]:

def khi2(crosstab):
    d = crosstab.shape
    if (len (d)  > 2):
        raise("Wrong format for this function")
    rows=d[0]  # unnecessary, but clear
    cols=d[1]  # unnecessary, but clear
    print("Degrees of freedom: ",(rows-1)*(cols-1))
    print("Marginal sums:\n")
    expecteds=margins3(crosstab)
    print(expecteds)
    print("\n")
    for k in range(rows):
        for l in range(cols):
            expecteds[k,l]=expecteds[k,cols]*expecteds[rows,l]/expecteds[rows,cols]
    print("Expected values:\n")
    print(expecteds)
    print("\n")
    sum = 0
    deviation=np.zeros((rows+1,cols+1))
    for k in range(rows):
        for l in range(cols):
            deviation[k,l]=((expecteds[k,l]-crosstab[k,l]))
            sum += deviation[k,l]**2/expecteds[k,l]

    print("A reminder about the observed values:")
    print("\n")
    print(crosstab)
    print("\n")
    print("Deviation from expected values:")
    print("\n")
    print(deviation)
    print("\n")
    print(sum)

khi2(crosstab)

Degrees of freedom:  1
Marginal sums:

[[       0.        0.  3860100.]
 [       0.        0.  1039831.]
 [   88985.  4810946.  4899931.]]


Expected values:

[[   70101.1909  3789998.8091  3860100.    ]
 [   18883.8091  1020947.1909  1039831.    ]
 [   88985.      4810946.      4899931.    ]]


A reminder about the observed values:


[[  69164 3790936]
 [  19821 1020010]]


Deviation from expected values:


[[ 937.1909 -937.1909    0.    ]
 [-937.1909  937.1909    0.    ]
 [   0.        0.        0.    ]]


60.1336311664


This value can be looked up in a prepared table of expected variation. 

https://people.richland.edu/james/lecture/m170/tbl-chi.html

### Exercise 7: the $\chi²$ test is not suitable when the expected values in any of the cells of a contingency table are below 5. There is a fix for this condition. 

### Exercise 8: Look up and implement Fisher's exact test 
(And you will find a use for the factorial $x!$ you learnt in the beginning of the class.)


# Discussion

- Long vs short words? Which test? ([w for w in v if len(w) > 15])
- Gender style? Which test?
- Ultimately significance testing is a question of convincing yourself and your future readers that you have observed something of general interest. A statistical test is one tool for that argument, but not a sufficient nor a necessary one. 


# Project ideas

- Mendenhall and other authorship attribution tests
- Gender differences in text
- Sentiment analysis
- Use API:s! 

